## buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci
  pre_build:
    commands:
  build:
    commands:
      - npm run start &
      - npx cypress run
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t borderfront:ui .
      - docker tag borderfront:ui 0045801317995.dkr.ecr.ca-central-1.amazonaws.com/border-front-fe     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 045801317995.dkr.ecr.ca-central-1.amazonaws.com/border-front-fe
      